ekf_node:
  ros__parameters:

    # Filter frequency and sensor timeout
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.1

    # Frames 
    world_frame: odom
    odom_frame: odom
    base_link_frame: base_footprint
    publish_tf: true
    publish_acceleration: false

    # Odometry input
    odom0: /odom
    odom0_config:  [true,  true,  false,  # x, y, z
                    false, false, false,  # roll, pitch, yaw
                    true,  true,  false,  # ẋ, ẏ, ż
                    false, false, true,   # roll̇, pitcḣ, yaẇ
                    false, false, false]  # ẍ, ÿ, z̈

    odom0_differential: false
    odom0_relative: false

    # IMU input
    imu0: /imu
    imu0_config:   [false, false, false,  # x, y, z
                    false, false, true,   # roll, pitch, yaw
                    false, false, false,  # ẋ, ẏ, ż
                    false, false, true,   # roll̇, pitcḣ, yaẇ
                    false, false, false]  # ẍ, ÿ, z̈

    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true