amcl:
  ros__parameters:
    use_sim_time: true
    odom_frame_id: odom
    base_frame_id: base_footprint
    odom_topic: /odometry/filtered
    scan_topic: /scan
    # keep other amcl defaults...

bt_navigator:
  ros__parameters:
    use_sim_time: true
    odom_topic: /odometry/filtered
    robot_base_frame: base_footprint

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 50
      model_dt: 0.1
      batch_size: 2000
      vx_std: 0.5
      vy_std: 0.3
      wz_std: 1.0
      vx_max: 1.5
      vx_min: -0.3
      vy_max: 1.0
      vy_min: -1.0
      wz_max: 1.0
      wz_min: -1.0
      iteration_count: 1
      prune_distance: 1.0
      transform_tolerance: 0.2

      critics: ["PathAlign", "GoalAlign", "ObstacleFootprint"]
      PathAlign:
        plugin: "nav2_mppi_controller::PathAlignCritic"
        scale: 2.0
      GoalAlign:
        plugin: "nav2_mppi_controller::GoalAlignCritic"
        scale: 2.0
      ObstacleFootprint:
        plugin: "nav2_mppi_controller::ObstacleFootprintCritic"
        scale: 3.0
        collision_cost: 1000.0


planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
# costmaps same as before
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        obstacle_range: 30.0
        raytrace_range: 30.0
        clearing: true
        marking: true
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        obstacle_range: 30.0
        raytrace_range: 30.0
        clearing: true
        marking: true
