### ekf config file ###
ekf_node:
    ros__parameters:
        frequency: 20.0
        sensor_timeout: 0.5
        two_d_mode: false
        publish_acceleration: true
        publish_tf: true

        odom_frame: odom
        base_link_frame: base_footprint
        world_frame: odom

        odom0: /odom
        odom0_config:  [false, false, false,
                        false, false, false,
                         true,  true, false,
                        false, false,  true,
                        false, false, false]

        imu0: /imu
        imu0_config:   [false, false, false,
                        false, false, false,
                         true,  true, false,
                        false, false,  true,
                        false, false, false]