slam_toolbox:
  ros__parameters:
    # ROS Parameters
    use_sim_time: true
    resolution: 0.05
    map_update_interval: 2.0
    max_laser_range: 30.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan
    use_map_saver: true
    scan_queue_size: 1000
    mode: mapping

