slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: "mapping"
    resolution: 0.05
    map_update_interval: 2.0
    max_laser_range: 30.0
    minimum_time_interval: 0.5
    map_frame: map  # transform_publish_period: 0.0
    odom_frame: odom           # or wamv/odom
    base_frame: base_link      # or wamv/base_link
    scan_topic: /scan
    publish_tf_map: true
    scan_queue_size: 1000      # <-- changed from queue_size
    transform_timeout: 0.2