# Configurazione Motori
engine:
  - prefix: "left"
    position: "-2.373776 1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "right"
    position: "-2.373776 -1.027135 0.318237"
    orientation: "0.0 0.0 0.0"

# Configurazione Thrusters
thruster_compliance_port_aft:
  pose: '-2.373776 1.027135 0.318237 0 0 0'
  size: '0.5 0.3 0.8'
  capacity: '1.0'

thruster_compliance_star_aft:
  pose: '-2.373776 -1.027135 0.318237 0 0 0'
  size: '0.5 0.3 0.8'
  capacity: '1.0'
  
# Configurazione Lidar
lidar:
  - name: gpu_lidar           
    type: VLP16               
    visualize: true           
    topic: /scan             
    x: 0.77                   
    y: 0.0                    
    z: 1.527                  
    R: 0.0                    
    P: 0.0                    
    Y: 0.0                    
    post_Y: 0.0               
    horizontal_samples: 640   
    vertical_samples: 16      
    min_range: 0.1            
    max_range: 30.0           
    noise_mean: 0.0           
    noise_stddev: 0.01        
